/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.faire

import faire.BackFill
import faire.NotifyAfter
import javax.inject.Inject

@NotifyAfter("2022-01-01")
class App @Inject constructor( val jayApp: JayApp): BackFill() {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
//    testSystemEnv()

}

private fun testSystemEnv() {
    println(System.getenv("JAVA_HOME"))
    println(System.getenv("jayName"))
    println("%,d".format(Int.MAX_VALUE))
    System.out.println(" Free Mem: " + Runtime.getRuntime().freeMemory() / (1024 * 1024));
    val memoryList = mutableListOf<Array<Int>>();
    for (i in 1..20) {
        println("Iteration $i Free Mem: ${Runtime.getRuntime().freeMemory() / (1024 * 1024)}");
        val memoryArray = Array(1_000_000) { i -> 0 }
//        val memoryArray = Array(Int.MAX_VALUE-1_000_000_000) { i -> 0 }
        memoryList.add(memoryArray)
        Thread.sleep(1000)
    }
}
