/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.faire

import faire.BackFill
import faire.NotifyAfter
import io.github.cdimascio.dotenv.Dotenv
import javax.inject.Inject

@NotifyAfter("2022-01-01")
class App @Inject constructor(val jayApp: GuiceTest) : BackFill() {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
//    testSystemEnv()
//    testMaxByOrNull()
//    testOOM()

}

private fun testMaxByOrNull() {
    val persons = listOf(Person("a", 1), Person("b", 2), Person("c", 3))
    persons.maxByOrNull(Person::age)
    persons.maxByOrNull { it.age }
}

private fun testSystemEnv() {
    System.getenv().entries.forEach { mutableEntry ->
        println(" ${mutableEntry.key} = ${mutableEntry.value}")
    }
    println(System.getenv("JAVA_HOME"))
    println(System.getenv("jayName"))
    println(System.getenv("SLACK_TOKEN"))
    println(System.getenv("jayzhou"))

    println("System.getenv(\"CODE_CLEANUP_BOT_SLACK_TOKEN\") = ${System.getenv("CODE_CLEANUP_BOT_SLACK_TOKEN")}")

    val dotenv = Dotenv.load();
    val slackToken = dotenv.get("CODE_CLEANUP_BOT_SLACK_TOKEN")
    println("slackToken = ${slackToken}")

}

private fun testOOM() {
    println("%,d".format(Int.MAX_VALUE))
    System.out.println(" Free Mem: " + Runtime.getRuntime().freeMemory() / (1024 * 1024));
    val memoryList = mutableListOf<Array<Int>>();
    for (i in 1..20) {
        println("Iteration $i Free Mem: ${Runtime.getRuntime().freeMemory() / (1024 * 1024)}");
        val memoryArray = Array(1_000_000) { i -> 0 }
//        val memoryArray = Array(Int.MAX_VALUE-1_000_000_000) { i -> 0 }
        memoryList.add(memoryArray)
        Thread.sleep(1000)
    }
}


data class Person(val name: String, val age: Int)