name: code cleanup notification
#on:
#  schedule:
#    - cron: "0 17 * * *" # daily at 17

on: [push]

jobs:
  code-cleanup-notification:
    name: cleanup notification job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Send out notification
        env:
          CODE_CLEANUP_BOT_SLACK_TOKEN: ${{ secrets.CODE_CLEANUP_BOT_SLACK_TOKEN }}
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: slack

#      - name: Cache Gradle packages
#        uses: actions/cache@v1
#        with:
#          path: ~/.gradle/caches
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
#          restore-keys: ${{ runner.os }}-gradle
#      - name: Send out notification
#        run: |
#          ./gradlew slack
#        env:
#          CODE_CLEANUP_BOT_SLACK_TOKEN: ${{ secrets.CODE_CLEANUP_BOT_SLACK_TOKEN }}
