name: code cleanup notification
on:
  schedule:
    - cron: "0 17 * * *" # daily at 17

#on: [push]

jobs:
  code-cleanup-notification:
    name: cleanup notification job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
#      - name: set git user
#        run: |
#          git config --global user.name "PR Bot"
#          git config --global user.email "pr-bot@faire.com"
#          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
#        env:
#          GITHUB_TOKEN: ${{ secrets.PR_BOT_GITHUB_TOKEN }}
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Send out notification
        run: |
          ./gradlew slack
        env:
          CODE_CLEANUP_BOT_SLACK_TOKEN: ${{ secrets.CODE_CLEANUP_BOT_SLACK_TOKEN }}
